<?php
if (function_exists('acf_add_local_field_group')) :

    acf_add_local_field_group(array(
        'key' => 'group_5f96d711606d5',
        'title' => 'Options',
        'fields' => array(
            array(
                'key' => 'field_5f96d79aad6c6',
                'label' => 'Form Settings',
                'name' => 'form_settings',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5f96d7c1ad6c7',
                        'label' => 'Campaign code',
                        'name' => 'source_code',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5f96d7ddad6c8',
                        'label' => 'Consent method',
                        'name' => 'consent_method',
                        'type' => 'radio',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'checkbox_checked' => 'Checkbox (checked)',
                            'checkbox_unchecked' => 'Checkbox (unchecked)',
                            'assumed' => 'Assumed',
                        ),
                        'allow_null' => 0,
                        'other_choice' => 0,
                        'default_value' => 'assumed',
                        'layout' => 'vertical',
                        'return_format' => 'value',
                        'save_other_choice' => 0,
                    ),
                    array(
                        'key' => 'field_5f96dba665c13',
                        'label' => 'Consent Message',
                        'name' => 'consent_message',
                        'type' => 'wysiwyg',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'tabs' => 'all',
                        'toolbar' => 'full',
                        'media_upload' => 1,
                        'delay' => 0,
                    ),
                    array(
                        'key' => 'field_5fa91ceeebc99',
                        'label' => 'Toggle form fields',
                        'name' => 'collapse_inputs',
                        'type' => 'radio',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'collapse' => 'Only show e-mail input until active',
                            'expand' => 'Show all form-fields from start',
                        ),
                        'allow_null' => 0,
                        'other_choice' => 0,
                        'default_value' => '',
                        'layout' => 'vertical',
                        'return_format' => 'value',
                        'save_other_choice' => 0,
                    ),
                    array(
                        'key' => 'field_5fa972fb027e6',
                        'label' => 'Enable counter',
                        'name' => 'enable_counter',
                        'type' => 'true_false',
                        'instructions' => 'Toggle the counter elements on both the form and the thank you page. The counter is always counting behind-the-scenes, which means this can be turned on at a later stage.',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => 'Display the counter',
                        'default_value' => 1,
                        'ui' => 0,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                    ),
                    array(
                        'key' => 'field_5fa972e9027e5',
                        'label' => 'Counter start value',
                        'name' => 'counter',
                        'type' => 'number',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_5fa972fb027e6',
                                    'operator' => '==',
                                    'value' => '1',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 0,
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'min' => '',
                        'max' => '',
                        'step' => '',
                    ),
                    // array(
                    //     'key' => 'field_5fce5e731f6f6',
                    //     'label' => 'Counter Start Value',
                    //     'name' => 'counter_start_value',
                    //     'type' => 'number',
                    //     'instructions' => '',
                    //     'required' => 0,
                    //     'conditional_logic' => array(
                    //         array(
                    //             array(
                    //                 'field' => 'field_5fa972fb027e6',
                    //                 'operator' => '==',
                    //                 'value' => '1',
                    //             ),
                    //         ),
                    //     ),
                    //     'wrapper' => array(
                    //         'width' => '',
                    //         'class' => '',
                    //         'id' => '',
                    //     ),
                    //     'default_value' => 0,
                    //     'placeholder' => '',
                    //     'prepend' => '',
                    //     'append' => '',
                    //     'min' => '',
                    //     'max' => '',
                    //     'step' => '',
                    // ),
                    array(
                        'key' => 'field_5fce5e731f6f6_counter_goal_value',
                        'label' => 'Counter goal value',
                        'name' => 'counter_goal_value',
                        'type' => 'number',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_5fa972fb027e6',
                                    'operator' => '==',
                                    'value' => '1',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 0,
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'min' => '',
                        'max' => '',
                        'step' => '',
                    ),
                    array(
                        'key' => 'field_5fce5e941f6f7',
                        'label' => 'Counter API-endpoints',
                        'name' => 'counter_api-endpoints',
                        'type' => 'repeater',
                        'instructions' => 'Every petition has an API-endpoint. By adding other petition API-endpoints to this list, the counter value of each will be added to this petition\'s displayed counter value.',
                        'required' => 0,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_5fa972fb027e6',
                                    'operator' => '==',
                                    'value' => '1',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'collapsed' => '',
                        'min' => 0,
                        'max' => 0,
                        'layout' => 'table',
                        'button_label' => '',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_5fce5ea91f6f8',
                                'label' => 'Endpoint',
                                'name' => 'endpoint',
                                'type' => 'url',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_5f96daf365c0f',
                        'label' => 'Phone',
                        'name' => 'phone',
                        'type' => 'radio',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'required' => 'Yes (required)',
                            'optional' => 'Yes (optional)',
                            'false' => 'No',
                        ),
                        'allow_null' => 0,
                        'other_choice' => 0,
                        'default_value' => 'optional',
                        'layout' => 'vertical',
                        'return_format' => 'value',
                        'save_other_choice' => 0,
                    ),
                    array(
                        'key' => 'field_5f96db2465c10',
                        'label' => 'Form headline',
                        'name' => 'headline',
                        'type' => 'textarea',
                        'instructions' => 'A short call to action is recommended.',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => 'Headline',
                        'maxlength' => 140,
                        'rows' => '',
                        'new_lines' => 'br',
                    ),
                    array(
                        'key' => 'field_5f96db5c65c11',
                        'label' => 'Form description',
                        'name' => 'description',
                        'type' => 'wysiwyg',
                        'instructions' => 'A small elaboration on the call to action.',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'tabs' => 'all',
                        'toolbar' => 'basic',
                        'media_upload' => 0,
                        'delay' => 0,
                    ),
                    array(
                        'key' => 'field_5f96db8765c12',
                        'label' => 'Form button text',
                        'name' => 'call_to_action',
                        'type' => 'text',
                        'instructions' => 'The called-for action. (sign now, join, stay updated, etc)',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => 'Call to action',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => 40,
                    ),
                ),
            ),
            array(
                'key' => 'field_5f97d3894eaef',
                'label' => 'Hero Settings',
                'name' => 'hero_settings',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5f97d3894eaf3',
                        'label' => 'Hero headline',
                        'name' => 'headline',
                        'type' => 'textarea',
                        'instructions' => 'The campaign title or slogan. Longer sentences will scale, but shorter texts are recommended.',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => 'Headline',
                        'maxlength' => 140,
                        'rows' => '',
                        'new_lines' => 'br',
                    ),
                    array(
                        'key' => 'field_5f97d3894eaf4',
                        'label' => 'Hero description',
                        'name' => 'description',
                        'type' => 'wysiwyg',
                        'instructions' => 'A brief campaign excerpt. Aim to keep this text concise and to-the-point. Use additional content blocks to elaborate on the matter. Texts longer than 300 characters will automatically be hidden under a \'read more\' link.',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'tabs' => 'all',
                        'toolbar' => 'basic',
                        'media_upload' => 0,
                        'delay' => 0,
                    ),
                ),
            ),
            array(
                'key' => 'field_5f97f5bebbcc8',
                'label' => 'Thank You Settings',
                'name' => 'thank_you_settings',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5f97f5bebbcc9',
                        'label' => 'Thank you headline',
                        'name' => 'headline',
                        'type' => 'text',
                        'instructions' => 'The variable ${fname} can be used to include the signers name.',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 'Thank you ${fname}!',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5f97f5bebbcca',
                        'label' => 'Thank you description',
                        'name' => 'description',
                        'type' => 'wysiwyg',
                        'instructions' => 'Tell the signer why we are thankful, what difference their signature will make, etc.',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'tabs' => 'all',
                        'toolbar' => 'basic',
                        'media_upload' => 0,
                        'delay' => 0,
                    ),
                    array(
                        'key' => 'field_5f97f89bbbccb',
                        'label' => 'Share headline',
                        'name' => 'share_headline',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 'Share',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5f97f8adbbccc',
                        'label' => 'Share description',
                        'name' => 'share_description',
                        'type' => 'wysiwyg',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'tabs' => 'all',
                        'toolbar' => 'basic',
                        'media_upload' => 0,
                        'delay' => 0,
                    ),
                    // array(
                    //     'key' => 'field_5f97fa02e53e8',
                    //     'label' => 'Share CTA',
                    //     'name' => 'share_cta',
                    //     'type' => 'text',
                    //     'instructions' => '',
                    //     'required' => 0,
                    //     'conditional_logic' => 0,
                    //     'wrapper' => array(
                    //         'width' => '',
                    //         'class' => '',
                    //         'id' => '',
                    //     ),
                    //     'default_value' => 'Spread the word',
                    //     'placeholder' => '',
                    //     'prepend' => '',
                    //     'append' => '',
                    //     'maxlength' => '',
                    // ),
                    array(
                        'key' => 'field_5fa917904b7fd',
                        'label' => 'Sharing text: Twitter',
                        'name' => 'twitter_share_text',
                        'type' => 'textarea',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => 100,
                        'rows' => '',
                        'new_lines' => '',
                    ),
                    array(
                        'key' => 'field_5fa922204b7fd',
                        'label' => 'Sharing text: Whatsapp',
                        'name' => 'whatsapp_share_text',
                        'type' => 'textarea',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => 100,
                        'rows' => '',
                        'new_lines' => '',
                    ),
                    array(
                        'key' => 'field_5f97fa02532352e8',
                        'label' => 'Sharing text: Email (subject)',
                        'name' => 'email_share_subject',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_546437f8c6bbcce',
                        'label' => 'Sharing text: Email (text)',
                        'name' => 'email_share_text',
                        'type' => 'textarea',
                        'instructions' => '%site_url% gets replaced with the url of the page',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 'Go check out %site_url%',
                        'placeholder' => '',
                        'maxlength' => 400,
                        'rows' => '',
                        'new_lines' => '',
                    ),
                    array(
                        'key' => 'field_5f97f8c0bbccd',
                        'label' => 'Donation ask headline',
                        'name' => 'donate_headline',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5f97f8c6bbcce',
                        'label' => 'Donation ask description',
                        'name' => 'donate_description',
                        'type' => 'wysiwyg',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'tabs' => 'all',
                        'toolbar' => 'basic',
                        'media_upload' => 0,
                        'delay' => 0,
                    ),
                    array(
                        'key' => 'field_5f97f8fabbcd0_default',
                        'label' => 'Default donation amount',
                        'name' => 'donate_default_amount',
                        'type' => 'number',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 10,
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'min' => '',
                        'max' => '',
                        'step' => '',
                    ),
                    array(
                        'key' => 'field_5f97fa2ce53e9',
                        'label' => 'Donation button text',
                        'name' => 'donate_cta',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5fa94bb74c24d',
                        'label' => 'Donation page URL',
                        'name' => 'donate_url',
                        'type' => 'text',
                        'instructions' => 'The checkout URL of the donation page, where %amount% is replaced by the user selected amount. The donation page can be changed by merely changing the \'page\' value in the URL below.',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'leads-form',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'seamless',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));

    acf_add_local_field_group(array(
        'key' => 'group_5f969db2d4824',
        'title' => 'Petition Form Block',
        'fields' => array(
            array(
                'key' => 'field_5f969dceef2b3',
                'label' => 'Display',
                'name' => 'display',
                'type' => 'radio',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'hero' => 'Hero',
                    'small' => 'Small',
                ),
                'allow_null' => 0,
                'other_choice' => 0,
                'default_value' => '',
                'layout' => 'vertical',
                'return_format' => 'value',
                'save_other_choice' => 0,
            ),
            array(
                'key' => 'field_5f96b4d4dd6ec',
                'label' => 'Form',
                'name' => 'form',
                'type' => 'post_object',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'post_type' => array(
                    0 => 'leads-form',
                ),
                'taxonomy' => '',
                'allow_null' => 0,
                'multiple' => 0,
                'return_format' => 'id',
                'ui' => 1,
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'block',
                    'operator' => '==',
                    'value' => 'acf/leads-form',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));

    acf_add_local_field_group(array(
        'key' => 'group_5f96a3336409b',
        'title' => 'Petition-wide settings',
        'fields' => array(
            array(
                'key' => 'field_5f96a33666d88',
                'label' => 'Connection',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5f96a35266d89',
                'label' => 'Host',
                'name' => 'database_host',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5f96a38a66d8a',
                'label' => 'Database Name',
                'name' => 'database_name',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5f96a39466d8b',
                'label' => 'Database User',
                'name' => 'database_user',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5f96a39f66d8c',
                'label' => 'Database Password',
                'name' => 'database_password',
                'type' => 'password',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_5f96a3b366d8d',
                'label' => 'SSL Certificate',
                'name' => 'ssl_certificate',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'new_lines' => '',
            ),
            array(
                'key' => 'field_5f96a58497512',
                'label' => 'Form Settings',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5f96a5a097513',
                'label' => 'Country Code ISO',
                'name' => 'country_code_iso',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'SE',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5f96a5c097514',
                'label' => 'Defaults & translations',
                'name' => 'form_fields_translations',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5f96a5d197515_goal',
                        'label' => 'Goal',
                        'name' => 'goal',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 'Goal',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5f96a5d197515_signed_up',
                        'label' => 'Signed up',
                        'name' => 'signed_up',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 'Signed up',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5f96a6159751a',
                        'label' => 'Read More',
                        'name' => 'read_more',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 'Read More',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    // array(
                    //     'key' => 'field_5f96a5d197515_read_more',
                    //     'label' => 'Read more',
                    //     'name' => 'read_more',
                    //     'type' => 'text',
                    //     'instructions' => '',
                    //     'required' => 0,
                    //     'conditional_logic' => 0,
                    //     'wrapper' => array(
                    //         'width' => '',
                    //         'class' => '',
                    //         'id' => '',
                    //     ),
                    //     'default_value' => 'Read more',
                    //     'placeholder' => '',
                    //     'prepend' => '',
                    //     'append' => '',
                    //     'maxlength' => '',
                    // ),
                    array(
                        'key' => 'field_5f96a5d197515_read_less',
                        'label' => 'Read less',
                        'name' => 'read_less',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 'Read less',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5f96a5d197515',
                        'label' => 'First Name',
                        'name' => 'first_name',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 'First Name',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5f96a5f597516',
                        'label' => 'Last Name',
                        'name' => 'last_name',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 'Last Name',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5f96a5fa97517',
                        'label' => 'E-mail',
                        'name' => 'email',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 'E-mail',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5f96a5ff97518',
                        'label' => 'Phone',
                        'name' => 'phone',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 'Phone',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5f96a60897519',
                        'label' => 'Country Code',
                        'name' => 'country_code',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '+46',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5f97e198e3c9b',
                        'label' => 'Sending',
                        'name' => 'sending',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 'Sending...',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5f97f8e7bbccf',
                        'label' => 'Donation currency',
                        'name' => 'donate_currency',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '€',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5f97f8fabbcd0',
                        'label' => 'Minimum donation amount',
                        'name' => 'donate_minimum_amount',
                        'type' => 'number',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 10,
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'min' => '',
                        'max' => '',
                        'step' => '',
                    ),
                    array(
                        'key' => 'field_5fa94bb74c24d_option',
                        'label' => 'Donate Url',
                        'name' => 'donate_url_option',
                        'type' => 'text',
                        'instructions' => 'Amount is replaced if written as: %amount%',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 'https://stod.greenpeace.org/checkout?amount=%amount%&page=engangsgava',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5f97d98e55f25',
                        'label' => 'Consent message (optional)',
                        'name' => 'terms_agree',
                        'type' => 'wysiwyg',
                        'instructions' => 'This is the default consent message. Only change this message if the data-handling deviates from the norm.',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 'I agree to the terms and conditions',
                        'tabs' => 'all',
                        'toolbar' => 'basic',
                        'media_upload' => 0,
                        'delay' => 0,
                    ),
                    array(
                        'key' => 'field_5f97e880a5e73',
                        'label' => 'Error (Required)',
                        'name' => 'error_required',
                        'type' => 'text',
                        'instructions' => 'The variable ${fieldName} inserts the field name.',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 'Required field "${fieldName}" has no value.',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5f97e8b8a5e74',
                        'label' => 'Error (Format)',
                        'name' => 'error_format',
                        'type' => 'text',
                        'instructions' => 'The variable ${fieldName} inserts the field name.',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 'Field "${fieldName}" has wrong format.',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'acf-options-leads-form',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));

    acf_add_local_field_group(array(
        'key' => 'group_5f96dbc96094b',
        'title' => 'Appearance',
        'fields' => array(
            array(
                'key' => 'field_5f96dbd8037d6',
                'label' => 'Styles',
                'name' => 'form_styles',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5f96dbfb037d7',
                        'label' => 'Placement',
                        'name' => 'placement',
                        'type' => 'radio',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'left' => 'Align Left',
                            'right' => 'Align Right',
                        ),
                        'allow_null' => 0,
                        'other_choice' => 0,
                        'default_value' => '',
                        'layout' => 'vertical',
                        'return_format' => 'value',
                        'save_other_choice' => 0,
                    ),
                    array(
                        'key' => 'field_5f96dc4c037d9',
                        'label' => 'Colors',
                        'name' => 'colors',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_5f96dc55037da',
                                'label' => 'Theme',
                                'name' => 'theme',
                                'type' => 'radio',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array(
                                    'light' => 'Light',
                                    'dark' => 'Dark',
                                ),
                                'allow_null' => 0,
                                'other_choice' => 0,
                                'default_value' => '',
                                'layout' => 'vertical',
                                'return_format' => 'value',
                                'save_other_choice' => 0,
                            ),
                            array(
                                'key' => 'field_5f96dc76037db',
                                'label' => 'Main color',
                                'name' => 'form_headline',
                                'type' => 'color_picker',
                                'instructions' => 'Applied to backgrounds of buttons/icons, links and the form heading.',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '#73BE1E',
                            ),
                            array(
                                'key' => 'field_5f96dc8b037dc',
                                'label' => 'Background overlay',
                                'name' => 'cta_background',
                                'type' => 'color_picker',
                                'instructions' => 'Applied to the background image and counter element. If the dark theme is selected, this color is applied to the form instead.',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '#005C42',
                            ),
                            array(
                                'key' => 'field_5f96dca5037dd',
                                'label' => 'CTA Text',
                                'name' => 'cta_text',
                                'type' => 'color_picker',
                                'instructions' => 'Applied to text and symbols on CTAs, buttons and icons.',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '#FFFFFF',
                            ),
                        ),
                    ),
                ),
            ),
            //
            array(
                'key' => 'field_5f9652337d6',
                'label' => 'Extra options',
                'name' => 'extra_options',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5f7a52379a452',
                        'label' => 'Small screen image',
                        'name' => 'small_screen_image',
                        'type' => 'image',
                        'instructions' => 'Can be used for when the selected background image (featured image) does not look ideal on e.g. mobile.',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'array',
                        'preview_size' => 'thumbnail',
                        'library' => 'all',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                    ),
                ),
            ),
            //
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'leads-form',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'side',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));

    function load_counter_api_field($field)
    {
        $rest_url = get_rest_url();
        $source_code = get_post_meta(get_the_ID(), 'form_settings_source_code', true);
        $field['instructions'] = "The endpoint for this form is <strong>{$rest_url}gplp/v2/leads/count/$source_code</strong>";
        return $field;
    }
    add_filter('acf/load_field/name=counter_api-endpoints', 'load_counter_api_field');

    function load_consent_message_field($field)
    {
        $default_value = get_option('options_form_fields_translations_terms_agree');
        $field['default_value'] = $default_value;
        return $field;
    }
    add_filter('acf/load_field/name=consent_message', 'load_consent_message_field');

    function load_donate_url_field($field)
    {
        $default_value = get_option('options_form_fields_translations_donate_url_option');
        $field['default_value'] = $default_value;
        return $field;
    }
    add_filter('acf/load_field/name=donate_url', 'load_donate_url_field');

endif;
